// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package recorddb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID        pgtype.UUID
	MachineID string
	Path      string
	Filename  string
	Size      int64
	Mtime     pgtype.Timestamp
	Hash      string
	CreatedAt pgtype.Timestamp
}
