// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package recorddb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertFile = `-- name: UpsertFile :exec
INSERT INTO files (machine_id, path, filename, size, mtime, hash)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (machine_id, path, filename)
DO UPDATE SET size = EXCLUDED.size, mtime = EXCLUDED.mtime, hash = EXCLUDED.hash
`

type UpsertFileParams struct {
	MachineID string
	Path      string
	Filename  string
	Size      int64
	Mtime     pgtype.Timestamp
	Hash      string
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) error {
	_, err := q.db.Exec(ctx, upsertFile,
		arg.MachineID,
		arg.Path,
		arg.Filename,
		arg.Size,
		arg.Mtime,
		arg.Hash,
	)
	return err
}
